---
title: "lab3_shiny"
author: "Siming Yan"
date: "7/13/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
textInput("fst_n", label = "Your first_name: ")
textInput("lst_n", label = "Your last_name: ")

# sliderInput("bw_adjust", label = "Bandwidth adjustment:",
#               min = 0.2, max = 2, value = 1, step = 0.2)
```

## output

```{r, echo = FALSE}
renderPrint({
   print(paste(input$fst_n, input$lst_n))
})
```


```{r, echo = F}
numericInput("v", label = "Value to be sqrted: ", 0)
```


```{r, echo = F}
renderPrint({

  if(input$v >= 0){
    print(sqrt(input$v))
  }
  else{
    print("Negative input!!!")
  }
})
```

```{r, include=F}

# func1 <- function (i,j){
#   i <- readline(prompt = "first-name: ")
#   j <- readline(prompt = "family-name: ")
#   t <- paste(i,j)
#   return(t)
#   # print(t)
# }
# 
# textInput("first-name: ", "family-name: ")
# 
# # renderTable({
# #   head(cars, input$rows)
# # })
# 
# renderPrint({
#   t
# })
```
 
 
 
```{r, include = F}
library(shiny)

ui <- fluidPage(
  titlePanel("censusVis"),
  
  sidebarLayout(
    sidebarPanel(
      helpText("Create demographic maps with 
               information from the 2010 US Census."),
      
      selectInput("var", 
                  label = "Choose a variable to display",
                  choices = c("Percent White", 
                              "Percent Black",
                              "Percent Hispanic", 
                              "Percent Asian"),
                  selected = "Percent White"),
      
      sliderInput("range", 
                  label = "Range of interest:",
                  min = 0, max = 100, value = c(0, 100))
    ),
    
    mainPanel(
      textOutput("selected_var"),
      textOutput("min_max")
    )
  )
)

server <- function(input, output) {
  
  output$selected_var <- renderText({ 
    paste("You have selected", input$var)
  })
  
  output$min_max <- renderText({ 
    paste("You have chosen a range that goes from",
          input$range[1], "to", input$range[2])
  })
  
}

shinyApp(ui, server)
```

